#SShader "Renderer/PostProcessing/Bloom/Up"

#type compute
layout(local_size_x = 4, local_size_y = 4, local_size_z = 1) in;

#include "Stulu/Renderer/PostProcessing/Bloom/Bloom.comp"

void main() {
	const ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

	vec3 highRes = TextureDSSourceLoad(pixelCoord);
	vec3 lowRes = Bloom_TentUp(pixelCoord);
	
	DestinationStore(vec4(BlendColors(highRes, lowRes), 1.0), pixelCoord);
}