#pragma once
#define USING_GLFW 1
#define OPENGL 1

#define ST_ENGINE_NAME ("Stulu Engine")
#define ST_ENGINE_VERSION_MAJOR 23
#define ST_ENGINE_VERSION_MINOR 12
#define ST_ENGINE_VERSION_PATCH 16

#if OPENGL == 0
	#define VULKAN
	#undef OPENGL
#else
	#define IMGUI_OPENGL_4 1
#endif

#ifdef ST_DEBUG
	#define ST_PROFILING 1
	#define ST_PROFILING_RENDERDATA 1

	#define ST_ENABLE_ASSERTS 1
	#define ST_ENABLE_ASSERTS_ONLY_LOGGING 1
	#define	ST_ENABLE_TRACE_LOGGING 1

	#define ST_GRAPHICS_API_DEBUG_LOGGING 1
	#define ST_GRAPHICS_API_INFO_LOGGING 0 // GL_DEBUG_SEVERITY_LOW | VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT
	#define ST_GRAPHICS_API_VERBOSE_LOGGING 0 // GL_DEBUG_SEVERITY_NOTIFICATION | VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT
#elif ST_RELEASE
	#define ST_PROFILING_RENDERDATA 1
	#define ST_GRAPHICS_API_DEBUG_LOGGING 1
	#define ST_ENABLE_ASSERTS 1

#elif ST_DIST
	#define ST_PROFILING_RENDERDATA 1
	#define ST_ENABLE_ASSERTS_ONLY_LOGGING 1
#endif