#pragma once

#ifdef ST_DEBUG
	#define ST_SHOWCONSOLE 1

	#define ST_PROFILING 1
	#define ST_PROFILING_RENDERDATA 1

	#define ST_LOG_FPS 0
	#define ST_ENABLE_ASSERTS 1
	#define ST_VULKAN_VERBOSE_LOGGING 0
	#define ST_VULKAN_INFO_LOGGING 1
#elif ST_RELEASE
	#define ST_SHOWCONSOLE 1

	#define ST_PROFILING 0
	#define ST_PROFILING_RENDERDATA 0

	#define ST_LOG_FPS 0
	#define ST_ENABLE_ASSERTS 1
	#define ST_VULKAN_VERBOSE_LOGGING 0
	#define ST_VULKAN_INFO_LOGGING 0
#elif ST_DIST
	#define ST_SHOWCONSOLE 0

	#define ST_PROFILING 0
	#define ST_PROFILING_RENDERDATA 0

	#define ST_LOG_FPS 0
	#define ST_ENABLE_ASSERTS 0
	#define ST_VULKAN_VERBOSE_LOGGING 0
	#define ST_VULKAN_INFO_LOGGING 0
#endif